baseURL = "https://wireguard.how/"
title = "WireGuard.How"
theme = "book"
ignoreFiles = ["^.+/content/snippet/.+$"]

[taxonomies]

[params]
  BookSection = '*'
  BookSearch = false
  BookDisqus = false
